[workspace]
resolver = "2"
members = ["nary_bin", "nary_lib"]

[profile.release]
debug = 1  # Enable line tables for backtraces

[workspace.dependencies]
# Shared dependencies
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "fs", "io-util"] }
reqwest = { version = "0.13", default-features = false, features = ["rustls", "json", "gzip", "brotli", "stream", "http2"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.3"
dirs = "6.0"
snafu = { version = "0.8", features = ["backtrace"] }
dashmap = "6.1"
pathdiff = "0.2"
node-semver = "2.2.0"
