[package]
name = "nary_bin"
version = "0.9.0"
authors = ["Grant Miner <gx0r@protonmail.com>"]
edition = "2018"
publish = false

[dependencies]
nary_lib = { path = "../nary_lib" }
snafu.workspace = true
reqwest.workspace = true
atty = "0.2"
bytesize = "2"
clap = { version = "4", features = ["derive"] }
owo-colors = { version = "4", features = ["supports-colors"] }
serde_json.workspace = true
serde_derive.workspace = true
dirs.workspace = true
indicatif = { version = "0.18", features = ["improved_unicode"] }
tokio.workspace = true
futures.workspace = true
terminal_size = "0.4"
dashmap.workspace = true
pathdiff.workspace = true
node-semver.workspace = true
tabled = "0.20"

[[bin]]
name = "nary"
path = "src/main.rs"
